{{- if .Values.configEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pandawa.fullname" . }}-config-env
  labels:
    {{- include "pandawa.api.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configEnv }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}
{{- end }}
