apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pandawa.fullname" . }}-api
  labels:
    {{- include "pandawa.api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.api.autoscaling.enabled}}
  replicas: {{.Values.api.replicaCount}}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pandawa.api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pandawa.api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pandawa.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "pandawa.fullname" . }}-api
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ (.Values.api.image | default .Values.image).repository }}:{{ (.Values.api.image | default .Values.image).tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ (.Values.api.image | default .Values.image).pullPolicy | default "IfNotPresent" }}
          command: {{ tpl (toJson .Values.api.command) . }}
          args: {{ tpl (toJson .Values.api.args) . }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: env
              readOnly: true
              mountPath: "/srv/app/.env"
              subPath: ".env"
            {{- with .Values.api.volumeMounts }}
            {{- tpl (toYaml .) $ | nindent 12 -}}
            {{- end }}
          {{- with .Values.api.livenessProbe }}
          livenessProbe:
            {{- tpl (toYaml .) $ | nindent 12 -}}
          {{- end }}
          {{- with .Values.api.readinessProbe }}
          readinessProbe:
            {{- tpl (toYaml .) $ | nindent 12 -}}
          {{- end }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
        {{- with .Values.api.sidecars }}
        {{- tpl (toYaml .) $ | nindent 8 -}}
        {{- end }}
      volumes:
        - name: env
          secret:
            secretName: {{ include "pandawa.fullname" . }}-env
        {{- with .Values.api.volumes }}
        {{- tpl (toYaml .) $ | nindent 8 -}}
        {{- end }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
