{{- if .Values.consumer.autoscaling.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "pandawa.fullname" . }}-consumer
  labels:
    {{- include "pandawa.consumer.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "pandawa.fullname" . }}-consumer
  minReplicas: {{ .Values.consumer.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.consumer.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.consumer.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.consumer.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.consumer.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.consumer.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  {{- with .Values.consumer.autoscaling.behavior }}
  behavior:
    {{- tpl (toYaml .) $ | nindent 4 -}}
  {{- end }}
{{- end }}
