{{- if .Values.ingress.enabled -}}
{{- if .Values.ingress.stripPrefixes }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "pandawa.fullname" . }}-stripprefix
  namespace: {{ .Release.Namespace }}
spec:
  stripPrefix:
    {{- with .Values.ingress.stripPrefixes }}
    prefixes:
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}
