apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pandawa.fullname" . }}-env
  labels:
    {{- include "pandawa.api.labels" . | nindent 4 }}
data:
  .env: {{ .Values.env | toString | b64enc }}
---
{{- if .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pandawa.fullname" . }}-secret-env
  labels:
    {{- include "pandawa.api.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
  {{- end }}
{{- end }}
