apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pandawa.fullname" . }}-env
  labels:
    {{- include "pandawa.api.labels" . | nindent 4 }}
data:
  .env: {{ .Values.env | toString | b64enc }}
