apiVersion: v1
kind: Service
metadata:
  name: {{ include "pandawa.fullname" . }}-api
  labels:
    {{- include "pandawa.api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pandawa.api.selectorLabels" . | nindent 4 }}
