nameOverride: ""
fullnameOverride: ""

image:
  repository: ""
  tag: ""
  pullPolicy: Always

containerPort: 3000

replicaCount: 1

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-cert-issuer
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

persistence:
  enabled: false
  mountPath: /data
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 1Gi

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: "50%"
    maxUnavailable: 0

podDisruptionBudget:
  enabled: false
  minAvailable: ""
  maxUnavailable: ""

podAnnotations:
  reloader.stakater.com/auto: "true"

configEnv: {}

extraEnvFrom: []

externalSecret: {}

imagePullSecrets: []

podSecurityContext: {}

securityContext: {}

serviceAccount:
  create: false
  name: ""
