{{- if .Values.externalSecret }}
{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "node-app.fullname" . }}
  labels:
    {{- include "node-app.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind | default "ClusterSecretStore" }}
  target:
    name: {{ .Values.externalSecret.target.name | default (printf "%s-env" (include "node-app.fullname" .)) }}
  dataFrom:
    {{- toYaml .Values.externalSecret.dataFrom | nindent 4 }}
{{- end }}
{{- end }}
